kind: pipeline
name: default

steps:
#- name: integrity_test
#  image: rzldt.azurecr.io/airzflow_test:latest
#  commands:
#    - echo DAGs Integrity Test
    #- airflow initdb
    #- cp --recursive /drone/src/dags /home/engineer/dags
    #- cd /home/engineer
    #- pytest -v --cov=/drone/src/dags --cov-report=term-missing -W ignore::DeprecationWarning --html=/drone/reports/report.html --self-contained-html /drone/src/dags/tests
#  volumes:
#    - name: docker
#      path: /var/run/docker.sock
#    - name: report
#      path: /drone/reports
#   image: plugins/gh-pages
#   settings:
#     username: 
#       from_secret: GITHUB_USER
#     password:
#       from_secret: GITHUB_PASSWORD
#     pages_directory: docs/build/html
#   when:
#     branch:
#     - master
#     event:
#       exclude:
#       - pull_request
- name: deploy_dags_qas
  image: python:3
  commands:
    - echo Deploying DAGs 
    - rm --force --recursive /dags/ipea_data
    - cp --recursive /drone/src/dags/ipea_data /dags/ipea_data
  volumes:
     - name: dags_qa
       path: /dags
  when:
    branch:
    - dev
    event:
      exclude:
        - pull_request
- name: deploy_dags_prd
  image: python:3
  commands:
    - echo Deploying DAGs 
    - rm --force --recursive /dags/ipea_data
    - cp --recursive /drone/src/dags/ipea_data /dags/ipea_data
  volumes:
     - name: dag_prd
       path: /dags
  when:
    branch:
    - master
    event:
      exclude:
        - pull_request
- name: failure_notify
  image: drillster/drone-email
  settings:
    host: 
      from_secret: DRONE_SMTP_HOST
    port:
      from_secret: DRONE_SMTP_PORT
    username: 
      from_secret: DRONE_EMAIL
    password:  
      from_secret: DRONE_PASSWORD
    from: 
      from_secret: DRONE_EMAIL
    attachment: /drone/reports/report.html
  volumes:
    - name: docker
      path: /var/run/docker.sock
    - name: report
      path: /drone/reports
  when:
    status: [ failure ]

volumes:
- name: dags_qa
  host:
    path: /mnt/airflow-qa/dags
- name: dag_prd
  host:
    path: /mnt/airflow-prd/dags
- name: docker
  host:
    path: /var/run/docker.sock
- name: report
  host:
    path: /home/droneafadm/reports
