kind: pipeline
type: kubernetes
name: default

steps:
- name: deploy_dags_prd
  image: bash
  privileged: true
  environment:
    SHARE_NAME: //raizendevstorage.file.core.windows.net/airflow/dags
    MOUNT_DIR: dags_dir
    SHARE_USERNAME: raizendevstorage
    SHARE_PASSWORD:
      from_secret: azure-storage-key  
  commands:
    - echo Deploying DAGs
    - mkdir $MOUNT_DIR
    - >
      mount -t cifs $SHARE_NAME $MOUNT_DIR -o 
      vers=3.0,username=$SHARE_USERNAME,password=$SHARE_PASSWORD,dir_mode=0777,file_mode=0777,serverino
    - rm -rf $MOUNT_DIR/ipea_data
    - cp --recursive /drone/src/dags/ipea_data $MOUNT_DIR/ipea_data
  when:
    branch:
    - master
    event:
      exclude:
        - pull_request
        - tag

- name: publish-image
  image: banzaicloud/drone-kaniko
  environment:
    GIT_USER:
      from_secret: GIT_USER
    GIT_PASSWORD:
      from_secret: GIT_PASSWORD
  settings:
    registry: raizenanalyticsdev.azurecr.io
    repo: ipea-data
    build_args_from_env:
      - GIT_USER
      - GIT_PASSWORD
    auto_tag: true
    username: raizenanalyticsdev
    password:
      from_secret: azure-registry-key
    context: /drone/src/docker/ondemand/
  when:
    branch:
    - dev-kubernetes
    event:
      - tag