version: '3'
services:

  redis:
    image: 'redis:3.2.7'
    restart: unless-stopped
    command: redis-server --requirepass redis123
    container_name: redis

  postgres:
    image: 'postgres:9.6'
    restart: unless-stopped
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./data/pgdata:/var/lib/postgresql/data/pgdata
    container_name: postgres

  webserver:
    image: rzldt.azurecr.io/airzflow:latest
    environment:
      - POSTGRES_HOST
      - POSTGRES_PORT
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - REDIS_HOST
      - REDIS_PORT
      - REDIS_PASSWORD
      - FERNET_KEY
      - REMOTE_BASE_LOG_FOLDER=./logs
      - ENVIRONMENT=dev
      - HOST_DAGS_PATH=./dags
    ports:
      - "127.0.0.1:8081:8080"
    command: airflow webserver
    restart: unless-stopped
    volumes:
      - ./dags:/home/engineer/dags:z
      - ./logs:/home/engineer/logs:z
      - /var/run/docker.sock:/var/run/docker.sock:ro

  scheduler:
    image: rzldt.azurecr.io/airzflow:latest
    environment:
      - POSTGRES_HOST
      - POSTGRES_PORT
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - REDIS_HOST
      - REDIS_PORT
      - REDIS_PASSWORD
      - FERNET_KEY
      - REMOTE_BASE_LOG_FOLDER
      - ENVIRONMENT=dev
      - HOST_DAGS_PATH=./dags
    command: airflow scheduler
    restart: unless-stopped
    volumes:
      - ./dags:/home/engineer/dags:z
      - ./logs:/home/engineer/logs:z
      - /var/run/docker.sock:/var/run/docker.sock:ro

  worker:
    image: rzldt.azurecr.io/airzflow:latest
    environment:
      - POSTGRES_HOST
      - POSTGRES_PORT
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - REDIS_HOST
      - REDIS_PORT
      - REDIS_PASSWORD
      - FERNET_KEY
      - REMOTE_BASE_LOG_FOLDER=./logs
      - ENVIRONMENT=dev
      - HOST_DAGS_PATH=./dags
      - HOST_LOGS_PATH=./logs
    command: airflow worker
    restart: unless-stopped
    volumes:
      - ./dags:/home/engineer/dags:z
      - ./logs:/home/engineer/logs:z
      - /var/run/docker.sock:/var/run/docker.sock:ro
  flower:
    image: rzldt.azurecr.io/airzflow:latest
    environment:
      - POSTGRES_HOST
      - POSTGRES_PORT
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - REDIS_HOST
      - REDIS_PORT
      - REDIS_PASSWORD
      - FERNET_KEY
      - REMOTE_BASE_LOG_FOLDER=./logs
      - ENVIRONMENT=dev
    command: airflow flower
    restart: unless-stopped
    ports:
      - "127.0.0.1:8082:5555"
